import { Company } from '@/types';

export const companies: Company[] = [
  // Technology (40)
  {
    name: 'Apple',
    domain: 'apple.com',
    sector: 'Technology',
    description: 'Designs and manufactures consumer electronics, software, and services including iPhone, Mac, and Apple Watch.',
    logoUrl: 'https://logo.clearbit.com/apple.com',
  },
  {
    name: 'Google',
    domain: 'google.com',
    sector: 'Technology',
    description: 'Provides internet-related products and services including search, advertising, cloud computing, and consumer hardware.',
    logoUrl: 'https://logo.clearbit.com/google.com',
  },
  {
    name: 'Microsoft',
    domain: 'microsoft.com',
    sector: 'Technology',
    description: 'Develops, manufactures, and supports software, hardware, and cloud services including Windows and Azure.',
    logoUrl: 'https://logo.clearbit.com/microsoft.com',
  },
  {
    name: 'Meta',
    domain: 'meta.com',
    sector: 'Technology',
    description: 'Operates social media platforms including Facebook, Instagram, WhatsApp, and develops virtual reality products.',
    logoUrl: 'https://logo.clearbit.com/meta.com',
  },
  {
    name: 'Amazon',
    domain: 'amazon.com',
    sector: 'Technology',
    description: 'E-commerce and cloud computing giant offering retail, streaming, and AWS cloud services.',
    logoUrl: 'https://logo.clearbit.com/amazon.com',
  },
  {
    name: 'Netflix',
    domain: 'netflix.com',
    sector: 'Technology',
    description: 'Streaming entertainment service producing original films and series for global audiences.',
    logoUrl: 'https://logo.clearbit.com/netflix.com',
  },
  {
    name: 'Tesla',
    domain: 'tesla.com',
    sector: 'Technology',
    description: 'Designs and manufactures electric vehicles, battery energy storage, and solar products.',
    logoUrl: 'https://logo.clearbit.com/tesla.com',
  },
  {
    name: 'NVIDIA',
    domain: 'nvidia.com',
    sector: 'Technology',
    description: 'Designs graphics processing units for gaming and professional markets, and AI computing chips.',
    logoUrl: 'https://logo.clearbit.com/nvidia.com',
  },
  {
    name: 'Adobe',
    domain: 'adobe.com',
    sector: 'Technology',
    description: 'Creates creative cloud software for design, photography, video, and marketing including Photoshop and Illustrator.',
    logoUrl: 'https://logo.clearbit.com/adobe.com',
  },
  {
    name: 'Salesforce',
    domain: 'salesforce.com',
    sector: 'Technology',
    description: 'Provides enterprise cloud computing solutions for customer relationship management and business applications.',
    logoUrl: 'https://logo.clearbit.com/salesforce.com',
  },
  {
    name: 'Oracle',
    domain: 'oracle.com',
    sector: 'Technology',
    description: 'Develops enterprise software for database management, cloud applications, and enterprise resource planning.',
    logoUrl: 'https://logo.clearbit.com/oracle.com',
  },
  {
    name: 'Intel',
    domain: 'intel.com',
    sector: 'Technology',
    description: 'Designs and manufactures semiconductors and computing platforms for servers and personal computers.',
    logoUrl: 'https://logo.clearbit.com/intel.com',
  },
  {
    name: 'AMD',
    domain: 'amd.com',
    sector: 'Technology',
    description: 'Designs and manufactures microprocessors and graphics processors for computing and gaming.',
    logoUrl: 'https://logo.clearbit.com/amd.com',
  },
  {
    name: 'Qualcomm',
    domain: 'qualcomm.com',
    sector: 'Technology',
    description: 'Develops semiconductors and wireless telecommunications technology for mobile devices.',
    logoUrl: 'https://logo.clearbit.com/qualcomm.com',
  },
  {
    name: 'IBM',
    domain: 'ibm.com',
    sector: 'Technology',
    description: 'Provides hybrid cloud, AI, and enterprise software and hardware solutions for businesses.',
    logoUrl: 'https://logo.clearbit.com/ibm.com',
  },
  {
    name: 'Cisco',
    domain: 'cisco.com',
    sector: 'Technology',
    description: 'Designs and sells networking equipment, software, and telecommunications technology.',
    logoUrl: 'https://logo.clearbit.com/cisco.com',
  },
  {
    name: 'SAP',
    domain: 'sap.com',
    sector: 'Technology',
    description: 'Provides enterprise resource planning software and business applications for operational efficiency.',
    logoUrl: 'https://logo.clearbit.com/sap.com',
  },
  {
    name: 'Spotify',
    domain: 'spotify.com',
    sector: 'Technology',
    description: 'Streaming platform offering music, podcasts, and audiobooks to millions of subscribers worldwide.',
    logoUrl: 'https://logo.clearbit.com/spotify.com',
  },
  {
    name: 'Uber',
    domain: 'uber.com',
    sector: 'Technology',
    description: 'Operates ridesharing, food delivery, and freight transportation platforms globally.',
    logoUrl: 'https://logo.clearbit.com/uber.com',
  },
  {
    name: 'Airbnb',
    domain: 'airbnb.com',
    sector: 'Technology',
    description: 'Online marketplace for lodging, homestays, and vacation rentals operated by hosts.',
    logoUrl: 'https://logo.clearbit.com/airbnb.com',
  },
  {
    name: 'Shopify',
    domain: 'shopify.com',
    sector: 'Technology',
    description: 'E-commerce platform enabling businesses to create online stores and manage retail operations.',
    logoUrl: 'https://logo.clearbit.com/shopify.com',
  },
  {
    name: 'Square',
    domain: 'squareup.com',
    sector: 'Technology',
    description: 'Provides payment processing and financial services for businesses and individuals.',
    logoUrl: 'https://logo.clearbit.com/squareup.com',
  },
  {
    name: 'Stripe',
    domain: 'stripe.com',
    sector: 'Technology',
    description: 'Financial infrastructure platform for online payment processing and commerce.',
    logoUrl: 'https://logo.clearbit.com/stripe.com',
  },
  {
    name: 'Twilio',
    domain: 'twilio.com',
    sector: 'Technology',
    description: 'Cloud communications platform for programmatic voice, video, and messaging APIs.',
    logoUrl: 'https://logo.clearbit.com/twilio.com',
  },
  {
    name: 'ServiceNow',
    domain: 'servicenow.com',
    sector: 'Technology',
    description: 'Provides enterprise IT service management and workflow automation software.',
    logoUrl: 'https://logo.clearbit.com/servicenow.com',
  },
  {
    name: 'Workday',
    domain: 'workday.com',
    sector: 'Technology',
    description: 'Cloud-based enterprise software for human resources, finance, and planning.',
    logoUrl: 'https://logo.clearbit.com/workday.com',
  },
  {
    name: 'Zoom',
    domain: 'zoom.us',
    sector: 'Technology',
    description: 'Provides video conferencing and unified communications as a service platform.',
    logoUrl: 'https://logo.clearbit.com/zoom.us',
  },
  {
    name: 'Slack',
    domain: 'slack.com',
    sector: 'Technology',
    description: 'Business communication platform for messaging, file sharing, and team collaboration.',
    logoUrl: 'https://logo.clearbit.com/slack.com',
  },
  {
    name: 'Atlassian',
    domain: 'atlassian.com',
    sector: 'Technology',
    description: 'Develops collaboration and productivity software including Jira and Confluence.',
    logoUrl: 'https://logo.clearbit.com/atlassian.com',
  },
  {
    name: 'DocuSign',
    domain: 'docusign.com',
    sector: 'Technology',
    description: 'Electronic signature and document management platform for digital agreements.',
    logoUrl: 'https://logo.clearbit.com/docusign.com',
  },
  {
    name: 'PayPal',
    domain: 'paypal.com',
    sector: 'Technology',
    description: 'Online payment system supporting money transfers and electronic commerce.',
    logoUrl: 'https://logo.clearbit.com/paypal.com',
  },
  {
    name: 'Intuit',
    domain: 'intuit.com',
    sector: 'Technology',
    description: 'Develops financial and tax preparation software including TurboTax and QuickBooks.',
    logoUrl: 'https://logo.clearbit.com/intuit.com',
  },
  {
    name: 'Broadcom',
    domain: 'broadcom.com',
    sector: 'Technology',
    description: 'Designs and supplies semiconductors and infrastructure software solutions.',
    logoUrl: 'https://logo.clearbit.com/broadcom.com',
  },
  {
    name: 'Texas Instruments',
    domain: 'ti.com',
    sector: 'Technology',
    description: 'Designs and manufactures semiconductors and integrated circuits for electronics.',
    logoUrl: 'https://logo.clearbit.com/ti.com',
  },
  {
    name: 'Dell Technologies',
    domain: 'dell.com',
    sector: 'Technology',
    description: 'Designs, develops, and manufactures personal computers and enterprise technology solutions.',
    logoUrl: 'https://logo.clearbit.com/dell.com',
  },
  {
    name: 'HP',
    domain: 'hp.com',
    sector: 'Technology',
    description: 'Manufactures personal computers, printers, and related supplies for consumers and businesses.',
    logoUrl: 'https://logo.clearbit.com/hp.com',
  },
  {
    name: 'Samsung Electronics',
    domain: 'samsung.com',
    sector: 'Technology',
    description: 'Produces consumer electronics, semiconductors, and telecommunications equipment globally.',
    logoUrl: 'https://logo.clearbit.com/samsung.com',
  },
  {
    name: 'Sony',
    domain: 'sony.com',
    sector: 'Technology',
    description: 'Manufactures consumer and professional electronics, gaming consoles, and entertainment content.',
    logoUrl: 'https://logo.clearbit.com/sony.com',
  },
  {
    name: 'LG',
    domain: 'lg.com',
    sector: 'Technology',
    description: 'Produces consumer electronics, home appliances, and display technologies.',
    logoUrl: 'https://logo.clearbit.com/lg.com',
  },
  {
    name: 'Snowflake',
    domain: 'snowflake.com',
    sector: 'Technology',
    description: 'Cloud-based data platform for data warehousing and analytics.',
    logoUrl: 'https://logo.clearbit.com/snowflake.com',
  },
  // Finance (25)
  {
    name: 'JPMorgan Chase',
    domain: 'jpmorganchase.com',
    sector: 'Finance',
    description: 'Global financial services firm providing investment banking, asset management, and consumer banking.',
    logoUrl: 'https://logo.clearbit.com/jpmorganchase.com',
  },
  {
    name: 'Goldman Sachs',
    domain: 'goldmansachs.com',
    sector: 'Finance',
    description: 'Global investment banking, securities, and investment management firm.',
    logoUrl: 'https://logo.clearbit.com/goldmansachs.com',
  },
  {
    name: 'Morgan Stanley',
    domain: 'morganstanley.com',
    sector: 'Finance',
    description: 'Investment bank and financial services company serving corporations and affluent clients.',
    logoUrl: 'https://logo.clearbit.com/morganstanley.com',
  },
  {
    name: 'Bank of America',
    domain: 'bankofamerica.com',
    sector: 'Finance',
    description: 'Multinational investment bank and financial services holding company.',
    logoUrl: 'https://logo.clearbit.com/bankofamerica.com',
  },
  {
    name: 'Citigroup',
    domain: 'citi.com',
    sector: 'Finance',
    description: 'Global investment bank and financial services corporation.',
    logoUrl: 'https://logo.clearbit.com/citi.com',
  },
  {
    name: 'Wells Fargo',
    domain: 'wellsfargo.com',
    sector: 'Finance',
    description: 'Diversified financial services company offering banking, investment, and mortgage products.',
    logoUrl: 'https://logo.clearbit.com/wellsfargo.com',
  },
  {
    name: 'Visa',
    domain: 'visa.com',
    sector: 'Finance',
    description: 'Global payments technology company connecting consumers, merchants, and financial institutions.',
    logoUrl: 'https://logo.clearbit.com/visa.com',
  },
  {
    name: 'Mastercard',
    domain: 'mastercard.com',
    sector: 'Finance',
    description: 'Global payment processing corporation facilitating credit and debit card transactions.',
    logoUrl: 'https://logo.clearbit.com/mastercard.com',
  },
  {
    name: 'American Express',
    domain: 'americanexpress.com',
    sector: 'Finance',
    description: 'Multinational financial services corporation specializing in charge and credit cards.',
    logoUrl: 'https://logo.clearbit.com/americanexpress.com',
  },
  {
    name: 'BlackRock',
    domain: 'blackrock.com',
    sector: 'Finance',
    description: 'World\'s largest asset manager providing investment management and risk management services.',
    logoUrl: 'https://logo.clearbit.com/blackrock.com',
  },
  {
    name: 'Charles Schwab',
    domain: 'schwab.com',
    sector: 'Finance',
    description: 'Banking and brokerage firm offering financial services and investment products.',
    logoUrl: 'https://logo.clearbit.com/schwab.com',
  },
  {
    name: 'Fidelity',
    domain: 'fidelity.com',
    sector: 'Finance',
    description: 'Financial services corporation providing investment management and brokerage services.',
    logoUrl: 'https://logo.clearbit.com/fidelity.com',
  },
  {
    name: 'Berkshire Hathaway',
    domain: 'berkshirehathaway.com',
    sector: 'Finance',
    description: 'Conglomerate holding company with diversified insurance, railroad, and manufacturing businesses.',
    logoUrl: 'https://logo.clearbit.com/berkshirehathaway.com',
  },
  {
    name: 'State Street',
    domain: 'statestreet.com',
    sector: 'Finance',
    description: 'Financial services and bank holding company specializing in institutional custody.',
    logoUrl: 'https://logo.clearbit.com/statestreet.com',
  },
  {
    name: 'KKR',
    domain: 'kkr.com',
    sector: 'Finance',
    description: 'Global investment firm specializing in private equity and alternative asset management.',
    logoUrl: 'https://logo.clearbit.com/kkr.com',
  },
  {
    name: 'Blackstone',
    domain: 'blackstone.com',
    sector: 'Finance',
    description: 'Alternative asset management and financial services firm.',
    logoUrl: 'https://logo.clearbit.com/blackstone.com',
  },
  {
    name: 'Carlyle Group',
    domain: 'carlyle.com',
    sector: 'Finance',
    description: 'Global investment firm managing private equity and credit funds.',
    logoUrl: 'https://logo.clearbit.com/carlyle.com',
  },
  {
    name: 'Apollo Global Management',
    domain: 'apollo.com',
    sector: 'Finance',
    description: 'Alternative investment manager specializing in private equity and credit.',
    logoUrl: 'https://logo.clearbit.com/apollo.com',
  },
  {
    name: 'HSBC',
    domain: 'hsbc.com',
    sector: 'Finance',
    description: 'British multinational universal bank and financial services holding company.',
    logoUrl: 'https://logo.clearbit.com/hsbc.com',
  },
  {
    name: 'Barclays',
    domain: 'barclays.com',
    sector: 'Finance',
    description: 'British multinational universal bank with investment banking and consumer divisions.',
    logoUrl: 'https://logo.clearbit.com/barclays.com',
  },
  {
    name: 'Deutsche Bank',
    domain: 'db.com',
    sector: 'Finance',
    description: 'German multinational investment bank and financial services company.',
    logoUrl: 'https://logo.clearbit.com/db.com',
  },
  {
    name: 'UBS',
    domain: 'ubs.com',
    sector: 'Finance',
    description: 'Swiss multinational investment bank and financial services company.',
    logoUrl: 'https://logo.clearbit.com/ubs.com',
  },
  {
    name: 'Credit Suisse',
    domain: 'credit-suisse.com',
    sector: 'Finance',
    description: 'Swiss investment bank and financial services firm.',
    logoUrl: 'https://logo.clearbit.com/credit-suisse.com',
  },
  {
    name: 'BNY Mellon',
    domain: 'bnymellon.com',
    sector: 'Finance',
    description: 'Global investments company providing asset management and custody services.',
    logoUrl: 'https://logo.clearbit.com/bnymellon.com',
  },
  {
    name: 'Northern Trust',
    domain: 'northerntrust.com',
    sector: 'Finance',
    description: 'Financial services company offering wealth management and asset servicing.',
    logoUrl: 'https://logo.clearbit.com/northerntrust.com',
  },
  // Healthcare/Pharma (20)
  {
    name: 'Pfizer',
    domain: 'pfizer.com',
    sector: 'Healthcare/Pharma',
    description: 'Pharmaceutical and biotechnology corporation developing vaccines and medicines.',
    logoUrl: 'https://logo.clearbit.com/pfizer.com',
  },
  {
    name: 'Johnson & Johnson',
    domain: 'jnj.com',
    sector: 'Healthcare/Pharma',
    description: 'Pharmaceutical and consumer health products corporation with medical devices division.',
    logoUrl: 'https://logo.clearbit.com/jnj.com',
  },
  {
    name: 'Merck',
    domain: 'merck.com',
    sector: 'Healthcare/Pharma',
    description: 'Global pharmaceutical company developing medicines and vaccines.',
    logoUrl: 'https://logo.clearbit.com/merck.com',
  },
  {
    name: 'AbbVie',
    domain: 'abbvie.com',
    sector: 'Healthcare/Pharma',
    description: 'Biopharmaceutical company focused on immunology and oncology therapeutics.',
    logoUrl: 'https://logo.clearbit.com/abbvie.com',
  },
  {
    name: 'Eli Lilly',
    domain: 'lilly.com',
    sector: 'Healthcare/Pharma',
    description: 'Pharmaceutical company developing medicines for diabetes, oncology, and neuroscience.',
    logoUrl: 'https://logo.clearbit.com/lilly.com',
  },
  {
    name: 'Bristol-Myers Squibb',
    domain: 'bms.com',
    sector: 'Healthcare/Pharma',
    description: 'Pharmaceutical company specializing in oncology and immunology drugs.',
    logoUrl: 'https://logo.clearbit.com/bms.com',
  },
  {
    name: 'Amgen',
    domain: 'amgen.com',
    sector: 'Healthcare/Pharma',
    description: 'Biotechnology company developing innovative human therapeutics.',
    logoUrl: 'https://logo.clearbit.com/amgen.com',
  },
  {
    name: 'Gilead Sciences',
    domain: 'gilead.com',
    sector: 'Healthcare/Pharma',
    description: 'Biopharmaceutical company focused on antiviral and oncology medicines.',
    logoUrl: 'https://logo.clearbit.com/gilead.com',
  },
  {
    name: 'Moderna',
    domain: 'modernatx.com',
    sector: 'Healthcare/Pharma',
    description: 'Biotechnology company developing mRNA therapeutics and vaccines.',
    logoUrl: 'https://logo.clearbit.com/modernatx.com',
  },
  {
    name: 'Regeneron',
    domain: 'regeneron.com',
    sector: 'Healthcare/Pharma',
    description: 'Biotechnology company developing medicines for eye diseases and inflammatory conditions.',
    logoUrl: 'https://logo.clearbit.com/regeneron.com',
  },
  {
    name: 'Vertex Pharmaceuticals',
    domain: 'vrtx.com',
    sector: 'Healthcare/Pharma',
    description: 'Biotechnology company developing therapies for cystic fibrosis and other diseases.',
    logoUrl: 'https://logo.clearbit.com/vrtx.com',
  },
  {
    name: 'Novartis',
    domain: 'novartis.com',
    sector: 'Healthcare/Pharma',
    description: 'Swiss multinational pharmaceutical company developing innovative medicines.',
    logoUrl: 'https://logo.clearbit.com/novartis.com',
  },
  {
    name: 'Roche',
    domain: 'roche.com',
    sector: 'Healthcare/Pharma',
    description: 'Swiss healthcare company specializing in pharmaceuticals and diagnostics.',
    logoUrl: 'https://logo.clearbit.com/roche.com',
  },
  {
    name: 'Sanofi',
    domain: 'sanofi.com',
    sector: 'Healthcare/Pharma',
    description: 'French multinational pharmaceutical company developing vaccines and medicines.',
    logoUrl: 'https://logo.clearbit.com/sanofi.com',
  },
  {
    name: 'AstraZeneca',
    domain: 'astrazeneca.com',
    sector: 'Healthcare/Pharma',
    description: 'British-Swedish pharmaceutical company developing oncology and respiratory medicines.',
    logoUrl: 'https://logo.clearbit.com/astrazeneca.com',
  },
  {
    name: 'GlaxoSmithKline',
    domain: 'gsk.com',
    sector: 'Healthcare/Pharma',
    description: 'Pharmaceutical and biotechnology company developing vaccines and medicines.',
    logoUrl: 'https://logo.clearbit.com/gsk.com',
  },
  {
    name: 'Bayer',
    domain: 'bayer.com',
    sector: 'Healthcare/Pharma',
    description: 'German multinational pharmaceutical and life sciences company.',
    logoUrl: 'https://logo.clearbit.com/bayer.com',
  },
  {
    name: 'UnitedHealth Group',
    domain: 'unitedhealthgroup.com',
    sector: 'Healthcare/Pharma',
    description: 'Health insurance and healthcare services company operating nationwide.',
    logoUrl: 'https://logo.clearbit.com/unitedhealthgroup.com',
  },
  {
    name: 'CVS Health',
    domain: 'cvshealth.com',
    sector: 'Healthcare/Pharma',
    description: 'Healthcare company operating pharmacy and retail health stores and insurance.',
    logoUrl: 'https://logo.clearbit.com/cvshealth.com',
  },
  {
    name: 'McKesson',
    domain: 'mckesson.com',
    sector: 'Healthcare/Pharma',
    description: 'Pharmaceutical distribution and healthcare information technology company.',
    logoUrl: 'https://logo.clearbit.com/mckesson.com',
  },
  // Energy (15)
  {
    name: 'ExxonMobil',
    domain: 'exxonmobil.com',
    sector: 'Energy',
    description: 'Multinational oil and gas corporation involved in exploration, production, and refining.',
    logoUrl: 'https://logo.clearbit.com/exxonmobil.com',
  },
  {
    name: 'Chevron',
    domain: 'chevron.com',
    sector: 'Energy',
    description: 'Multinational energy corporation engaged in oil and gas exploration and production.',
    logoUrl: 'https://logo.clearbit.com/chevron.com',
  },
  {
    name: 'Shell',
    domain: 'shell.com',
    sector: 'Energy',
    description: 'British multinational oil and gas company operating across the energy sector.',
    logoUrl: 'https://logo.clearbit.com/shell.com',
  },
  {
    name: 'BP',
    domain: 'bp.com',
    sector: 'Energy',
    description: 'British multinational oil and gas company with renewable energy investments.',
    logoUrl: 'https://logo.clearbit.com/bp.com',
  },
  {
    name: 'TotalEnergies',
    domain: 'totalenergies.com',
    sector: 'Energy',
    description: 'French multinational integrated oil and gas company with renewable energy focus.',
    logoUrl: 'https://logo.clearbit.com/totalenergies.com',
  },
  {
    name: 'ConocoPhillips',
    domain: 'conocophillips.com',
    sector: 'Energy',
    description: 'Independent exploration and production company focused on oil and natural gas.',
    logoUrl: 'https://logo.clearbit.com/conocophillips.com',
  },
  {
    name: 'Marathon Petroleum',
    domain: 'marathonpetroleum.com',
    sector: 'Energy',
    description: 'Refining, marketing, and midstream energy company operating across the US.',
    logoUrl: 'https://logo.clearbit.com/marathonpetroleum.com',
  },
  {
    name: 'Valero Energy',
    domain: 'valero.com',
    sector: 'Energy',
    description: 'International manufacturer and marketer of transportation fuels and petrochemicals.',
    logoUrl: 'https://logo.clearbit.com/valero.com',
  },
  {
    name: 'Phillips 66',
    domain: 'phillips66.com',
    sector: 'Energy',
    description: 'Diversified energy manufacturing and logistics company.',
    logoUrl: 'https://logo.clearbit.com/phillips66.com',
  },
  {
    name: 'Occidental Petroleum',
    domain: 'oxy.com',
    sector: 'Energy',
    description: 'International oil and gas exploration and production company.',
    logoUrl: 'https://logo.clearbit.com/oxy.com',
  },
  {
    name: 'Schlumberger',
    domain: 'slb.com',
    sector: 'Energy',
    description: 'Oilfield services company providing technology for reservoir characterization and drilling.',
    logoUrl: 'https://logo.clearbit.com/slb.com',
  },
  {
    name: 'Halliburton',
    domain: 'halliburton.com',
    sector: 'Energy',
    description: 'Oilfield services company providing products and services for petroleum exploration.',
    logoUrl: 'https://logo.clearbit.com/halliburton.com',
  },
  {
    name: 'Baker Hughes',
    domain: 'bakerhughes.com',
    sector: 'Energy',
    description: 'Energy technology company providing oilfield services and equipment.',
    logoUrl: 'https://logo.clearbit.com/bakerhughes.com',
  },
  {
    name: 'Enbridge',
    domain: 'enbridge.com',
    sector: 'Energy',
    description: 'Canadian energy infrastructure company operating pipelines and utilities.',
    logoUrl: 'https://logo.clearbit.com/enbridge.com',
  },
  {
    name: 'NextEra Energy',
    domain: 'nexteraenergy.com',
    sector: 'Energy',
    description: 'Electric power company with significant renewable energy generation.',
    logoUrl: 'https://logo.clearbit.com/nexteraenergy.com',
  },
  // Consumer/Retail (25)
  {
    name: 'Walmart',
    domain: 'walmart.com',
    sector: 'Consumer/Retail',
    description: 'Multinational retail corporation operating hypermarkets and e-commerce.',
    logoUrl: 'https://logo.clearbit.com/walmart.com',
  },
  {
    name: 'Nike',
    domain: 'nike.com',
    sector: 'Consumer/Retail',
    description: 'Designs, develops, and sells athletic footwear, apparel, and equipment.',
    logoUrl: 'https://logo.clearbit.com/nike.com',
  },
  {
    name: 'McDonald\'s',
    domain: 'mcdonalds.com',
    sector: 'Consumer/Retail',
    description: 'Fast food restaurant chain serving burgers, fries, and breakfast globally.',
    logoUrl: 'https://logo.clearbit.com/mcdonalds.com',
  },
  {
    name: 'Coca-Cola',
    domain: 'coca-cola.com',
    sector: 'Consumer/Retail',
    description: 'Beverage corporation producing soft drinks and non-alcoholic beverages worldwide.',
    logoUrl: 'https://logo.clearbit.com/coca-cola.com',
  },
  {
    name: 'Target',
    domain: 'target.com',
    sector: 'Consumer/Retail',
    description: 'General merchandise retailer offering apparel, home goods, and electronics.',
    logoUrl: 'https://logo.clearbit.com/target.com',
  },
  {
    name: 'Home Depot',
    domain: 'homedepot.com',
    sector: 'Consumer/Retail',
    description: 'Home improvement retailer selling tools, construction products, and services.',
    logoUrl: 'https://logo.clearbit.com/homedepot.com',
  },
  {
    name: 'Costco',
    domain: 'costco.com',
    sector: 'Consumer/Retail',
    description: 'Membership warehouse club offering bulk merchandise at discount prices.',
    logoUrl: 'https://logo.clearbit.com/costco.com',
  },
  {
    name: 'Lowe\'s',
    domain: 'lowes.com',
    sector: 'Consumer/Retail',
    description: 'Home improvement retailer selling tools, appliances, and building materials.',
    logoUrl: 'https://logo.clearbit.com/lowes.com',
  },
  {
    name: 'Starbucks',
    domain: 'starbucks.com',
    sector: 'Consumer/Retail',
    description: 'Coffeehouse chain roasting and selling specialty coffee and beverages.',
    logoUrl: 'https://logo.clearbit.com/starbucks.com',
  },
  {
    name: 'Adidas',
    domain: 'adidas.com',
    sector: 'Consumer/Retail',
    description: 'Multinational corporation designing and manufacturing sports shoes and apparel.',
    logoUrl: 'https://logo.clearbit.com/adidas.com',
  },
  {
    name: 'Lululemon',
    domain: 'lululemon.com',
    sector: 'Consumer/Retail',
    description: 'Athletic apparel retailer specializing in yoga and fitness clothing.',
    logoUrl: 'https://logo.clearbit.com/lululemon.com',
  },
  {
    name: 'TJ Maxx',
    domain: 'tjmaxx.com',
    sector: 'Consumer/Retail',
    description: 'Off-price retail chain offering discounted apparel and home fashions.',
    logoUrl: 'https://logo.clearbit.com/tjmaxx.com',
  },
  {
    name: 'Best Buy',
    domain: 'bestbuy.com',
    sector: 'Consumer/Retail',
    description: 'Consumer electronics retailer selling computers, appliances, and entertainment.',
    logoUrl: 'https://logo.clearbit.com/bestbuy.com',
  },
  {
    name: 'Macy\'s',
    domain: 'macys.com',
    sector: 'Consumer/Retail',
    description: 'Department store chain offering apparel, home goods, and beauty products.',
    logoUrl: 'https://logo.clearbit.com/macys.com',
  },
  {
    name: 'Nordstrom',
    domain: 'nordstrom.com',
    sector: 'Consumer/Retail',
    description: 'Premium department store chain offering fashion and beauty products.',
    logoUrl: 'https://logo.clearbit.com/nordstrom.com',
  },
  {
    name: 'Gap',
    domain: 'gap.com',
    sector: 'Consumer/Retail',
    description: 'Apparel retailer offering casual clothing for men, women, and children.',
    logoUrl: 'https://logo.clearbit.com/gap.com',
  },
  {
    name: 'Under Armour',
    domain: 'underarmour.com',
    sector: 'Consumer/Retail',
    description: 'Sports apparel and accessories company producing performance clothing.',
    logoUrl: 'https://logo.clearbit.com/underarmour.com',
  },
  {
    name: 'Dollar General',
    domain: 'dollargeneral.com',
    sector: 'Consumer/Retail',
    description: 'Discount retailer offering groceries, household items, and seasonal merchandise.',
    logoUrl: 'https://logo.clearbit.com/dollargeneral.com',
  },
  {
    name: 'Kroger',
    domain: 'kroger.com',
    sector: 'Consumer/Retail',
    description: 'Supermarket chain operating grocery stores and pharmacies across the US.',
    logoUrl: 'https://logo.clearbit.com/kroger.com',
  },
  {
    name: 'Albertsons',
    domain: 'albertsons.com',
    sector: 'Consumer/Retail',
    description: 'Grocery store chain operating supermarkets and pharmacies.',
    logoUrl: 'https://logo.clearbit.com/albertsons.com',
  },
  {
    name: 'Dollar Tree',
    domain: 'dollartree.com',
    sector: 'Consumer/Retail',
    description: 'Discount variety store chain selling products at fixed price points.',
    logoUrl: 'https://logo.clearbit.com/dollartree.com',
  },
  {
    name: 'Bath & Body Works',
    domain: 'bathandbodyworks.com',
    sector: 'Consumer/Retail',
    description: 'Retailer specializing in fragrance, body care, and home fragrance products.',
    logoUrl: 'https://logo.clearbit.com/bathandbodyworks.com',
  },
  {
    name: 'Ulta Beauty',
    domain: 'ulta.com',
    sector: 'Consumer/Retail',
    description: 'Beauty retailer offering cosmetics, fragrance, and salon services.',
    logoUrl: 'https://logo.clearbit.com/ulta.com',
  },
  {
    name: 'Sephora',
    domain: 'sephora.com',
    sector: 'Consumer/Retail',
    description: 'Beauty retailer offering cosmetics, skincare, and fragrance products.',
    logoUrl: 'https://logo.clearbit.com/sephora.com',
  },
  {
    name: 'Etsy',
    domain: 'etsy.com',
    sector: 'Consumer/Retail',
    description: 'E-commerce marketplace for handmade, vintage, and unique goods.',
    logoUrl: 'https://logo.clearbit.com/etsy.com',
  },
  // Media/Entertainment (15)
  {
    name: 'Disney',
    domain: 'disney.com',
    sector: 'Media/Entertainment',
    description: 'Entertainment conglomerate operating theme parks, film studios, and streaming services.',
    logoUrl: 'https://logo.clearbit.com/disney.com',
  },
  {
    name: 'Warner Bros. Discovery',
    domain: 'wbd.com',
    sector: 'Media/Entertainment',
    description: 'Mass media and entertainment conglomerate producing films and television content.',
    logoUrl: 'https://logo.clearbit.com/wbd.com',
  },
  {
    name: 'Comcast',
    domain: 'comcast.com',
    sector: 'Media/Entertainment',
    description: 'Telecommunications conglomerate providing cable, internet, and NBCUniversal content.',
    logoUrl: 'https://logo.clearbit.com/comcast.com',
  },
  {
    name: 'Paramount Global',
    domain: 'paramount.com',
    sector: 'Media/Entertainment',
    description: 'Mass media conglomerate operating film studios and television networks.',
    logoUrl: 'https://logo.clearbit.com/paramount.com',
  },
  {
    name: 'Sony Pictures',
    domain: 'sonypictures.com',
    sector: 'Media/Entertainment',
    description: 'Film and television production and distribution company.',
    logoUrl: 'https://logo.clearbit.com/sonypictures.com',
  },
  {
    name: 'Lionsgate',
    domain: 'lionsgate.com',
    sector: 'Media/Entertainment',
    description: 'Film and television production and distribution company.',
    logoUrl: 'https://logo.clearbit.com/lionsgate.com',
  },
  {
    name: 'Fox Corporation',
    domain: 'foxcorporation.com',
    sector: 'Media/Entertainment',
    description: 'Mass media company operating broadcast television and news networks.',
    logoUrl: 'https://logo.clearbit.com/foxcorporation.com',
  },
  {
    name: 'News Corp',
    domain: 'newscorp.com',
    sector: 'Media/Entertainment',
    description: 'Mass media conglomerate operating newspapers and book publishing.',
    logoUrl: 'https://logo.clearbit.com/newscorp.com',
  },
  {
    name: 'Warner Music Group',
    domain: 'warnermusic.com',
    sector: 'Media/Entertainment',
    description: 'Record label and music publishing company representing artists worldwide.',
    logoUrl: 'https://logo.clearbit.com/warnermusic.com',
  },
  {
    name: 'Live Nation',
    domain: 'livenation.com',
    sector: 'Media/Entertainment',
    description: 'Live entertainment company promoting concerts and operating venues.',
    logoUrl: 'https://logo.clearbit.com/livenation.com',
  },
  {
    name: 'DraftKings',
    domain: 'draftkings.com',
    sector: 'Media/Entertainment',
    description: 'Digital sports entertainment and gaming company offering fantasy sports.',
    logoUrl: 'https://logo.clearbit.com/draftkings.com',
  },
  {
    name: 'Electronic Arts',
    domain: 'ea.com',
    sector: 'Media/Entertainment',
    description: 'Video game publisher developing sports and action titles.',
    logoUrl: 'https://logo.clearbit.com/ea.com',
  },
  {
    name: 'Take-Two Interactive',
    domain: 'take2games.com',
    sector: 'Media/Entertainment',
    description: 'Video game publisher known for Grand Theft Auto and NBA 2K franchises.',
    logoUrl: 'https://logo.clearbit.com/take2games.com',
  },
  {
    name: 'Activision Blizzard',
    domain: 'activisionblizzard.com',
    sector: 'Media/Entertainment',
    description: 'Video game publisher developing Call of Duty and World of Warcraft.',
    logoUrl: 'https://logo.clearbit.com/activisionblizzard.com',
  },
  {
    name: 'Universal Music Group',
    domain: 'universalmusic.com',
    sector: 'Media/Entertainment',
    description: 'Music corporation operating record labels and music publishing.',
    logoUrl: 'https://logo.clearbit.com/universalmusic.com',
  },
  // Automotive (15)
  {
    name: 'Toyota',
    domain: 'toyota.com',
    sector: 'Automotive',
    description: 'Japanese automotive manufacturer producing cars, trucks, and hybrids.',
    logoUrl: 'https://logo.clearbit.com/toyota.com',
  },
  {
    name: 'BMW',
    domain: 'bmw.com',
    sector: 'Automotive',
    description: 'German luxury automaker producing cars and motorcycles.',
    logoUrl: 'https://logo.clearbit.com/bmw.com',
  },
  {
    name: 'Ford',
    domain: 'ford.com',
    sector: 'Automotive',
    description: 'American automaker producing trucks, cars, and electric vehicles.',
    logoUrl: 'https://logo.clearbit.com/ford.com',
  },
  {
    name: 'General Motors',
    domain: 'gm.com',
    sector: 'Automotive',
    description: 'American automaker producing vehicles under Chevrolet, GMC, and Cadillac brands.',
    logoUrl: 'https://logo.clearbit.com/gm.com',
  },
  {
    name: 'Stellantis',
    domain: 'stellantis.com',
    sector: 'Automotive',
    description: 'Multinational automaker formed from Fiat Chrysler and PSA Group merger.',
    logoUrl: 'https://logo.clearbit.com/stellantis.com',
  },
  {
    name: 'Mercedes-Benz',
    domain: 'mercedes-benz.com',
    sector: 'Automotive',
    description: 'German luxury automaker producing premium cars and commercial vehicles.',
    logoUrl: 'https://logo.clearbit.com/mercedes-benz.com',
  },
  {
    name: 'Volkswagen',
    domain: 'volkswagen.com',
    sector: 'Automotive',
    description: 'German automaker producing vehicles under VW, Audi, and Porsche brands.',
    logoUrl: 'https://logo.clearbit.com/volkswagen.com',
  },
  {
    name: 'Honda',
    domain: 'honda.com',
    sector: 'Automotive',
    description: 'Japanese manufacturer producing automobiles, motorcycles, and power equipment.',
    logoUrl: 'https://logo.clearbit.com/honda.com',
  },
  {
    name: 'Nissan',
    domain: 'nissan-global.com',
    sector: 'Automotive',
    description: 'Japanese automaker producing cars, trucks, and electric vehicles.',
    logoUrl: 'https://logo.clearbit.com/nissan-global.com',
  },
  {
    name: 'Hyundai',
    domain: 'hyundai.com',
    sector: 'Automotive',
    description: 'South Korean automaker producing cars and SUVs under Hyundai and Genesis brands.',
    logoUrl: 'https://logo.clearbit.com/hyundai.com',
  },
  {
    name: 'Rivian',
    domain: 'rivian.com',
    sector: 'Automotive',
    description: 'Electric vehicle manufacturer producing trucks and SUVs.',
    logoUrl: 'https://logo.clearbit.com/rivian.com',
  },
  {
    name: 'Lucid Motors',
    domain: 'lucidmotors.com',
    sector: 'Automotive',
    description: 'Electric vehicle manufacturer producing luxury sedans.',
    logoUrl: 'https://logo.clearbit.com/lucidmotors.com',
  },
  {
    name: 'Ferrari',
    domain: 'ferrari.com',
    sector: 'Automotive',
    description: 'Italian luxury sports car manufacturer producing high-performance vehicles.',
    logoUrl: 'https://logo.clearbit.com/ferrari.com',
  },
  {
    name: 'Porsche',
    domain: 'porsche.com',
    sector: 'Automotive',
    description: 'German luxury automaker producing sports cars and SUVs.',
    logoUrl: 'https://logo.clearbit.com/porsche.com',
  },
  {
    name: 'BorgWarner',
    domain: 'borgwarner.com',
    sector: 'Automotive',
    description: 'Automotive components supplier specializing in powertrain and propulsion systems.',
    logoUrl: 'https://logo.clearbit.com/borgwarner.com',
  },
  // Aerospace/Defense (10)
  {
    name: 'Boeing',
    domain: 'boeing.com',
    sector: 'Aerospace/Defense',
    description: 'Aerospace and defense corporation manufacturing commercial airplanes and military aircraft.',
    logoUrl: 'https://logo.clearbit.com/boeing.com',
  },
  {
    name: 'Lockheed Martin',
    domain: 'lockheedmartin.com',
    sector: 'Aerospace/Defense',
    description: 'Aerospace and defense technology company developing military aircraft and missiles.',
    logoUrl: 'https://logo.clearbit.com/lockheedmartin.com',
  },
  {
    name: 'Raytheon Technologies',
    domain: 'rtx.com',
    sector: 'Aerospace/Defense',
    description: 'Aerospace and defense company producing missiles, radars, and aircraft engines.',
    logoUrl: 'https://logo.clearbit.com/rtx.com',
  },
  {
    name: 'Northrop Grumman',
    domain: 'northropgrumman.com',
    sector: 'Aerospace/Defense',
    description: 'Aerospace and defense technology company developing military systems and spacecraft.',
    logoUrl: 'https://logo.clearbit.com/northropgrumman.com',
  },
  {
    name: 'General Dynamics',
    domain: 'gd.com',
    sector: 'Aerospace/Defense',
    description: 'Aerospace and defense corporation producing combat vehicles and submarines.',
    logoUrl: 'https://logo.clearbit.com/gd.com',
  },
  {
    name: 'BAE Systems',
    domain: 'baesystems.com',
    sector: 'Aerospace/Defense',
    description: 'British multinational arms, security, and aerospace company.',
    logoUrl: 'https://logo.clearbit.com/baesystems.com',
  },
  {
    name: 'L3Harris Technologies',
    domain: 'l3harris.com',
    sector: 'Aerospace/Defense',
    description: 'Technology company developing defense and intelligence solutions.',
    logoUrl: 'https://logo.clearbit.com/l3harris.com',
  },
  {
    name: 'Airbus',
    domain: 'airbus.com',
    sector: 'Aerospace/Defense',
    description: 'European aerospace corporation manufacturing commercial aircraft and helicopters.',
    logoUrl: 'https://logo.clearbit.com/airbus.com',
  },
  {
    name: 'SpaceX',
    domain: 'spacex.com',
    sector: 'Aerospace/Defense',
    description: 'Aerospace manufacturer and space transportation company developing rockets.',
    logoUrl: 'https://logo.clearbit.com/spacex.com',
  },
  {
    name: 'General Electric Aerospace',
    domain: 'geaerospace.com',
    sector: 'Aerospace/Defense',
    description: 'Aircraft engine and aerospace systems manufacturer.',
    logoUrl: 'https://logo.clearbit.com/geaerospace.com',
  },
  // Telecom (10)
  {
    name: 'AT&T',
    domain: 'att.com',
    sector: 'Telecom',
    description: 'Multinational telecommunications conglomerate providing wireless and broadband services.',
    logoUrl: 'https://logo.clearbit.com/att.com',
  },
  {
    name: 'Verizon',
    domain: 'verizon.com',
    sector: 'Telecom',
    description: 'Telecommunications company providing wireless and fiber network services.',
    logoUrl: 'https://logo.clearbit.com/verizon.com',
  },
  {
    name: 'T-Mobile',
    domain: 't-mobile.com',
    sector: 'Telecom',
    description: 'Wireless network operator providing mobile phone and internet services.',
    logoUrl: 'https://logo.clearbit.com/t-mobile.com',
  },
  {
    name: 'Lumen Technologies',
    domain: 'lumen.com',
    sector: 'Telecom',
    description: 'Telecommunications company providing fiber network and cloud connectivity services.',
    logoUrl: 'https://logo.clearbit.com/lumen.com',
  },
  {
    name: 'Charter Communications',
    domain: 'charter.com',
    sector: 'Telecom',
    description: 'Cable operator providing broadband, cable television, and telephone services.',
    logoUrl: 'https://logo.clearbit.com/charter.com',
  },
  {
    name: 'Vodafone',
    domain: 'vodafone.com',
    sector: 'Telecom',
    description: 'British multinational telecommunications company operating mobile networks globally.',
    logoUrl: 'https://logo.clearbit.com/vodafone.com',
  },
  {
    name: 'Deutsche Telekom',
    domain: 'telekom.com',
    sector: 'Telecom',
    description: 'German telecommunications company operating across Europe and the US.',
    logoUrl: 'https://logo.clearbit.com/telekom.com',
  },
  {
    name: 'Orange',
    domain: 'orange.com',
    sector: 'Telecom',
    description: 'French telecommunications operator providing mobile and fixed-line services.',
    logoUrl: 'https://logo.clearbit.com/orange.com',
  },
  {
    name: 'BT Group',
    domain: 'bt.com',
    sector: 'Telecom',
    description: 'British telecommunications company providing fixed-line and mobile services.',
    logoUrl: 'https://logo.clearbit.com/bt.com',
  },
  {
    name: 'Ericsson',
    domain: 'ericsson.com',
    sector: 'Telecom',
    description: 'Swedish telecommunications company providing network equipment and services.',
    logoUrl: 'https://logo.clearbit.com/ericsson.com',
  },
  // Food/Beverage (15)
  {
    name: 'Nestlé',
    domain: 'nestle.com',
    sector: 'Food/Beverage',
    description: 'Swiss multinational food and drink processing conglomerate.',
    logoUrl: 'https://logo.clearbit.com/nestle.com',
  },
  {
    name: 'PepsiCo',
    domain: 'pepsico.com',
    sector: 'Food/Beverage',
    description: 'Beverage and snack corporation producing Pepsi, Lay\'s, and Quaker products.',
    logoUrl: 'https://logo.clearbit.com/pepsico.com',
  },
  {
    name: 'Kraft Heinz',
    domain: 'kraftheinzcompany.com',
    sector: 'Food/Beverage',
    description: 'Food and beverage company producing condiments, cheese, and packaged meals.',
    logoUrl: 'https://logo.clearbit.com/kraftheinzcompany.com',
  },
  {
    name: 'Mondelez International',
    domain: 'mondelezinternational.com',
    sector: 'Food/Beverage',
    description: 'Snack food company producing Oreo, Cadbury, and Toblerone brands.',
    logoUrl: 'https://logo.clearbit.com/mondelezinternational.com',
  },
  {
    name: 'General Mills',
    domain: 'generalmills.com',
    sector: 'Food/Beverage',
    description: 'Food company producing cereals, yogurt, and baking products.',
    logoUrl: 'https://logo.clearbit.com/generalmills.com',
  },
  {
    name: 'Kellogg\'s',
    domain: 'kelloggs.com',
    sector: 'Food/Beverage',
    description: 'Food manufacturing company producing cereals and snacks.',
    logoUrl: 'https://logo.clearbit.com/kelloggs.com',
  },
  {
    name: 'Campbell Soup',
    domain: 'campbellsoupcompany.com',
    sector: 'Food/Beverage',
    description: 'Food company producing soups, sauces, and snacks.',
    logoUrl: 'https://logo.clearbit.com/campbellsoupcompany.com',
  },
  {
    name: 'Conagra Brands',
    domain: 'conagrabrands.com',
    sector: 'Food/Beverage',
    description: 'Packaged foods company producing frozen meals and grocery brands.',
    logoUrl: 'https://logo.clearbit.com/conagrabrands.com',
  },
  {
    name: 'Hershey',
    domain: 'hersheys.com',
    sector: 'Food/Beverage',
    description: 'Chocolate and confectionery company producing Hershey\'s candy and chocolate.',
    logoUrl: 'https://logo.clearbit.com/hersheys.com',
  },
  {
    name: 'Mars',
    domain: 'mars.com',
    sector: 'Food/Beverage',
    description: 'Confectionery and pet food company producing M&M\'s, Snickers, and Pedigree.',
    logoUrl: 'https://logo.clearbit.com/mars.com',
  },
  {
    name: 'Unilever',
    domain: 'unilever.com',
    sector: 'Food/Beverage',
    description: 'Consumer goods company producing food, beverages, and cleaning products.',
    logoUrl: 'https://logo.clearbit.com/unilever.com',
  },
  {
    name: 'Diageo',
    domain: 'diageo.com',
    sector: 'Food/Beverage',
    description: 'Alcoholic beverage company producing spirits and beer brands.',
    logoUrl: 'https://logo.clearbit.com/diageo.com',
  },
  {
    name: 'AB InBev',
    domain: 'ab-inbev.com',
    sector: 'Food/Beverage',
    description: 'Multinational drink and brewing company producing beer brands globally.',
    logoUrl: 'https://logo.clearbit.com/ab-inbev.com',
  },
  {
    name: 'Constellation Brands',
    domain: 'cbrands.com',
    sector: 'Food/Beverage',
    description: 'Alcoholic beverage company producing wine, beer, and spirits.',
    logoUrl: 'https://logo.clearbit.com/cbrands.com',
  },
  {
    name: 'Sysco',
    domain: 'sysco.com',
    sector: 'Food/Beverage',
    description: 'Food distribution company supplying restaurants and food service operations.',
    logoUrl: 'https://logo.clearbit.com/sysco.com',
  },
  // Other notable/controversial (10)
  {
    name: 'Purdue Pharma',
    domain: 'purduepharma.com',
    sector: 'Other notable/controversial',
    description: 'Pharmaceutical company that manufactured OxyContin, central to opioid litigation.',
    logoUrl: 'https://logo.clearbit.com/purduepharma.com',
  },
  {
    name: 'Philip Morris International',
    domain: 'pminvestor.com',
    sector: 'Other notable/controversial',
    description: 'Tobacco company manufacturing cigarettes and developing smoke-free products.',
    logoUrl: 'https://logo.clearbit.com/pminvestor.com',
  },
  {
    name: 'Altria',
    domain: 'altria.com',
    sector: 'Other notable/controversial',
    description: 'Tobacco company owning Marlboro and investing in nicotine alternatives.',
    logoUrl: 'https://logo.clearbit.com/altria.com',
  },
  {
    name: 'WeWork',
    domain: 'wework.com',
    sector: 'Other notable/controversial',
    description: 'Co-working space company that collapsed amid governance and valuation controversies.',
    logoUrl: 'https://logo.clearbit.com/wework.com',
  },
  {
    name: 'Juul Labs',
    domain: 'juul.com',
    sector: 'Other notable/controversial',
    description: 'E-cigarette company that faced regulatory scrutiny over youth vaping.',
    logoUrl: 'https://logo.clearbit.com/juul.com',
  },
  {
    name: 'Monsanto',
    domain: 'monsanto.com',
    sector: 'Other notable/controversial',
    description: 'Agrochemical company acquired by Bayer, known for herbicide Roundup.',
    logoUrl: 'https://logo.clearbit.com/monsanto.com',
  },
  {
    name: 'McKinsey & Company',
    domain: 'mckinsey.com',
    sector: 'Other notable/controversial',
    description: 'Management consulting firm that has faced scrutiny over opioid and other client work.',
    logoUrl: 'https://logo.clearbit.com/mckinsey.com',
  },
  {
    name: 'Glencore',
    domain: 'glencore.com',
    sector: 'Other notable/controversial',
    description: 'Commodities trading and mining company that has faced corruption investigations.',
    logoUrl: 'https://logo.clearbit.com/glencore.com',
  },
  {
    name: 'Palantir',
    domain: 'palantir.com',
    sector: 'Other notable/controversial',
    description: 'Data analytics company facing scrutiny over government surveillance contracts.',
    logoUrl: 'https://logo.clearbit.com/palantir.com',
  },
  {
    name: 'Theranos',
    domain: 'theranos.com',
    sector: 'Other notable/controversial',
    description: 'Defunct health technology company that perpetrated blood-testing fraud.',
    logoUrl: 'https://logo.clearbit.com/theranos.com',
  },
];
